### PR TITLE
Removes Google Plus link

### PR DESCRIPTION
**Pull request by kittysquee**
@tosbourn Please review 😺

### CODE REVIEW

**Comment by tosbourn** [comment]
Please review CSS and remove `.google` since it will no longer be required.

**Comment by kittysquee** [comment]
@tosbourn the CSS has been removed 😺

**Comment by tosbourn** [comment]
@kittysquee with tosbourn.com the CSS needs to be manually minified, without doing so `.google` will still appear on the CSS that is loaded on every page.

**Comment by kittysquee** [comment]
- Minifies CSS file
- Removes duplicate Jekyll author post 
- Changes `Want to work with me in the future?` to `Want to work with us in the future?`

**Pull request merged**
