### PR TITLE
Remove all social media tracking tools

### PR DESCRIPTION
**Pull request by kittysquee**

### CODE REVIEW

**Comment by kittysquee** [comment]
@tosbourn what was the rationale for removing this tracking anyway?

**Comment by tosbourn** [comment]
@kittysquee we weren't using it for anything and extra JS for no reason is 👎

**Comment by kittysquee** [comment]
Are they just used to track where users have originated?

**Comment by tosbourn** [comment]
Basically - So from inside each social network we could get data to say "this month 100 tweets generated traffic to these pages" or similar. Never looked at the data and don't have any reason to think we would need to soon.

When I added it my thinking was "better to have it and not need it" but with things like GDPR and privacy being high on folks radar, the less stuff we track without needing to the better I think.

I'm going to run lighthouse once it is deployed to see if it helps with anything speed related.

**Pull request merged**
